### ISSUE TITLE
Creating a new MySQL database - fetching user fails

### ISSUE THREAD

**Issue by etlam** [mittwald/cli#270]
Creating a new MySQL database works, but fetching the created user fails:

```
mw database mysql create --description="my description" --version="8.0"

  Creating a new MySQL database

  ❓ enter password for default user: ******************************************************************************************************************************** 
  ✅ creating MySQL database. done
  ✅ fetching database. done
  ❌ fetching user. error

     An error occurred during this operation:
     ApiClientError: Unexpected response status (expected 200, got: 403)

╭──────────────────────────────────────────────────────────────────────────────╮
│ API CLIENT ERROR                                                             │
│                                                                              │
│ An error occurred while communicating with the API: Unexpected response      │
│ status (expected 200, got: 403)                                              │
│                                                                              │
│ {                                                                            │
│   "params": {                                                                │
│     "traceId": "f727d21f1f6ad105"                                            │
│   },                                                                         │
│   "message": "access denied; verdict: abstain",                              │
│   "type": "PermissionDenied"                                                 │
│ }                                                                            │
╰──────────────────────────────────────────────────────────────────────────────╯

  ERROR STACK TRACE

  Please provide this when opening a bug report.

  ApiClientError: Unexpected response status (expected 200, got: 403)
      at ApiClientError.fromResponse (file:///var/lib/nvm/versions/node/v18.17.0/lib/node_modules/@mittwald/cli/node_modules/@mittwald/api-client-commons/dist/esm/core/ApiClientError.js:9:16)
      at assertOneOfStatus (file:///var/lib/nvm/versions/node/v18.17.0/lib/node_modules/@mittwald/cli/node_modules/@mittwald/api-client-commons/dist/esm/types/assertOneOfStatus.js:4:30)
      at assertStatus (file:///var/lib/nvm/versions/node/v18.17.0/lib/node_modules/@mittwald/cli/node_modules/@mittwald/api-client-commons/dist/esm/types/assertStatus.js:3:5)
      at file:///var/lib/nvm/versions/node/v18.17.0/lib/node_modules/@mittwald/cli/dist/commands/database/mysql/create.js:86:13
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async FancyProcessRenderer.runStep (file:///var/lib/nvm/versions/node/v18.17.0/lib/node_modules/@mittwald/cli/dist/rendering/process/process_fancy.js:42:28)
      at async Create.exec (file:///var/lib/nvm/versions/node/v18.17.0/lib/node_modules/@mittwald/cli/dist/commands/database/mysql/create.js:82:22)
      at async Create.run (file:///var/lib/nvm/versions/node/v18.17.0/lib/node_modules/@mittwald/cli/dist/rendering/react/ExecRenderBaseCommand.js:18:24)
      at async Create._run (/var/lib/nvm/versions/node/v18.17.0/lib/node_modules/@mittwald/cli/node_modules/@oclif/core/lib/command.js:304:22)
      at async Config.runCommand (/var/lib/nvm/versions/node/v18.17.0/lib/node_modules/@mittwald/cli/node_modules/@oclif/core/lib/config/config.js:426:25)

```

**Comment by martin-helmich** [comment]
Thanks for the report, we'll investigate. 🕵️   I'm hoping that this is "just" some eventual-consistency issue, in which the created user is not available just immediately after the creation of the database.

**Comment by martin-helmich** [comment]
@etlam This should be fixed (well, mitigated, at least...) in the [latest release](https://github.com/mittwald/cli/releases/tag/v1.0.0-alpha.38). It actually takes a few seconds for a database user to be actually available via the API, which the CLI didn't account for until #279.
