### ISSUE TITLE
ddev pull mittwald leads to 403

### ISSUE THREAD

**Issue by DaRe92** [mittwald/cli#305]
When i try the `ddev pull mittwald` i get the following error after long time of waiting:

```
╭──────────────────────────────────────────────────────────────────────────────╮
│ ERROR                                                                        │
│                                                                              │
│ An error occurred while executing this command:                              │
│                                                                              │
│   AxiosError: Request failed with status code 403                            │
│                                                                              │
│ If you believe this to be a bug, please open an issue at                     │
│ https://github.com/mittwald/cli/issues/new                                   │
│ (​https://github.com/mittwald/cli/issues/new​).                              │
╰──────────────────────────────────────────────────────────────────────────────╯

  ERROR STACK TRACE

  Please provide this when opening a bug report.

  AxiosError: Request failed with status code 403
      at settle (file:///usr/lib/node_modules/@mittwald/cli/node_modules/axios/lib/core/settle.js:19:12)
      at IncomingMessage.handleStreamEnd (file:///usr/lib/node_modules/@mittwald/cli/node_modules/axios/lib/adapters/http.js:589:11)
      at IncomingMessage.emit (node:events:529:35)
      at endReadableNT (node:internal/streams/readable:1400:12)
      at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
      at Axios.request (file:///usr/lib/node_modules/@mittwald/cli/node_modules/axios/lib/core/Axios.js:45:41)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async Axios.request (file:///usr/lib/node_modules/@mittwald/cli/node_modules/axios/lib/core/Axios.js:40:14)
      at async Axios.request (file:///usr/lib/node_modules/@mittwald/cli/node_modules/axios/lib/core/Axios.js:40:14)
      at async Axios.request (file:///usr/lib/node_modules/@mittwald/cli/node_modules/axios/lib/core/Axios.js:40:14)
      at async Axios.request (file:///usr/lib/node_modules/@mittwald/cli/node_modules/axios/lib/core/Axios.js:40:14)
      at async Axios.request (file:///usr/lib/node_modules/@mittwald/cli/node_modules/axios/lib/core/Axios.js:40:14)
      at async Axios.request (file:///usr/lib/node_modules/@mittwald/cli/node_modules/axios/lib/core/Axios.js:40:14)
      at async Axios.request (file:///usr/lib/node_modules/@mittwald/cli/node_modules/axios/lib/core/Axios.js:40:14)
      at async Axios.request (file:///usr/lib/node_modules/@mittwald/cli/node_modules/axios/lib/core/Axios.js:40:14)
      at Axios.request (file:///usr/lib/node_modules/@mittwald/cli/node_modules/axios/lib/core/Axios.js:45:41)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async Axios.request (file:///usr/lib/node_modules/@mittwald/cli/node_modules/axios/lib/core/Axios.js:40:14)
      at async Axios.request (file:///usr/lib/node_modules/@mittwald/cli/node_modules/axios/lib/core/Axios.js:40:14)
      at async Axios.request (file:///usr/lib/node_modules/@mittwald/cli/node_modules/axios/lib/core/Axios.js:40:14)
      at async Axios.request (file:///usr/lib/node_modules/@mittwald/cli/node_modules/axios/lib/core/Axios.js:40:14)
      at async Axios.request (file:///usr/lib/node_modules/@mittwald/cli/node_modules/axios/lib/core/Axios.js:40:14)
      at async Axios.request (file:///usr/lib/node_modules/@mittwald/cli/node_modules/axios/lib/core/Axios.js:40:14)
      at async Axios.request (file:///usr/lib/node_modules/@mittwald/cli/node_modules/axios/lib/core/Axios.js:40:14)
      at async normalizeAppInstallationId (file:///usr/lib/node_modules/@mittwald/cli/dist/normalize_id.js:29:30)
      at Axios.request (file:///usr/lib/node_modules/@mittwald/cli/node_modules/axios/lib/core/Axios.js:45:41)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async Axios.request (file:///usr/lib/node_modules/@mittwald/cli/node_modules/axios/lib/core/Axios.js:40:14)
      at async Axios.request (file:///usr/lib/node_modules/@mittwald/cli/node_modules/axios/lib/core/Axios.js:40:14)
      at async Axios.request (file:///usr/lib/node_modules/@mittwald/cli/node_modules/axios/lib/core/Axios.js:40:14)
      at async Axios.request (file:///usr/lib/node_modules/@mittwald/cli/node_modules/axios/lib/core/Axios.js:40:14)
      at async Axios.request (file:///usr/lib/node_modules/@mittwald/cli/node_modules/axios/lib/core/Axios.js:40:14)
      at async Axios.request (file:///usr/lib/node_modules/@mittwald/cli/node_modules/axios/lib/core/Axios.js:40:14)
      at async normalizeAppInstallationId (file:///usr/lib/node_modules/@mittwald/cli/dist/normalize_id.js:29:30)
      at async Set.run (file:///usr/lib/node_modules/@mittwald/cli/dist/commands/context/set.js:42:36)
      at Axios.request (file:///usr/lib/node_modules/@mittwald/cli/node_modules/axios/lib/core/Axios.js:45:41)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async Axios.request (file:///usr/lib/node_modules/@mittwald/cli/node_modules/axios/lib/core/Axios.js:40:14)
      at async Axios.request (file:///usr/lib/node_modules/@mittwald/cli/node_modules/axios/lib/core/Axios.js:40:14)
      at async Axios.request (file:///usr/lib/node_modules/@mittwald/cli/node_modules/axios/lib/core/Axios.js:40:14)
      at async Axios.request (file:///usr/lib/node_modules/@mittwald/cli/node_modules/axios/lib/core/Axios.js:40:14)
      at async Axios.request (file:///usr/lib/node_modules/@mittwald/cli/node_modules/axios/lib/core/Axios.js:40:14)
      at async normalizeAppInstallationId (file:///usr/lib/node_modules/@mittwald/cli/dist/normalize_id.js:29:30)
      at async Set.run (file:///usr/lib/node_modules/@mittwald/cli/dist/commands/context/set.js:42:36)
      at async Set._run (/usr/lib/node_modules/@mittwald/cli/node_modules/@oclif/core/lib/command.js:304:22)
      at Axios.request (file:///usr/lib/node_modules/@mittwald/cli/node_modules/axios/lib/core/Axios.js:45:41)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async Axios.request (file:///usr/lib/node_modules/@mittwald/cli/node_modules/axios/lib/core/Axios.js:40:14)
      at async Axios.request (file:///usr/lib/node_modules/@mittwald/cli/node_modules/axios/lib/core/Axios.js:40:14)
      at async Axios.request (file:///usr/lib/node_modules/@mittwald/cli/node_modules/axios/lib/core/Axios.js:40:14)
      at async Axios.request (file:///usr/lib/node_modules/@mittwald/cli/node_modules/axios/lib/core/Axios.js:40:14)
      at async normalizeAppInstallationId (file:///usr/lib/node_modules/@mittwald/cli/dist/normalize_id.js:29:30)
      at async Set.run (file:///usr/lib/node_modules/@mittwald/cli/dist/commands/context/set.js:42:36)
      at async Set._run (/usr/lib/node_modules/@mittwald/cli/node_modules/@oclif/core/lib/command.js:304:22)
      at async Config.runCommand (/usr/lib/node_modules/@mittwald/cli/node_modules/@oclif/core/lib/config/config.js:432:25)
      at Axios.request (file:///usr/lib/node_modules/@mittwald/cli/node_modules/axios/lib/core/Axios.js:45:41)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async Axios.request (file:///usr/lib/node_modules/@mittwald/cli/node_modules/axios/lib/core/Axios.js:40:14)
      at async Axios.request (file:///usr/lib/node_modules/@mittwald/cli/node_modules/axios/lib/core/Axios.js:40:14)
      at async Axios.request (file:///usr/lib/node_modules/@mittwald/cli/node_modules/axios/lib/core/Axios.js:40:14)
      at async normalizeAppInstallationId (file:///usr/lib/node_modules/@mittwald/cli/dist/normalize_id.js:29:30)
      at async Set.run (file:///usr/lib/node_modules/@mittwald/cli/dist/commands/context/set.js:42:36)
      at async Set._run (/usr/lib/node_modules/@mittwald/cli/node_modules/@oclif/core/lib/command.js:304:22)
      at async Config.runCommand (/usr/lib/node_modules/@mittwald/cli/node_modules/@oclif/core/lib/config/config.js:432:25)
      at async Object.run (/usr/lib/node_modules/@mittwald/cli/node_modules/@oclif/core/lib/main.js:87:16)
Pull failed: exit status 1
```

A working API key and SSH user are stored. I can use all functions such as app list or app create, so I assume that I have both read and write access to my apps.

**Comment by martin-helmich** [comment]
Thanks for your feedback. Can you check if an `MITTWALD_API_TOKEN` environment variable is configured in your `web_configuration` setting (either per-project or globally)? Usually, the `mittwald/ddev` addon should have prompted you for one on installation, but maybe that didn't work out in this case. 🤔 

As a workaround: If there is no `MITTWALD_API_TOKEN` environment variable set, you can set the token manually using (in general, I'd recommend setting it either globally, or in a `config.local.yaml`, as to not check your token into version control accidentally):

```
$ ddev config global --web-environment-add MITTWALD_API_TOKEN=${token}
```

Or, if you already have a working CLI login:

```
$ ddev config global --web-environment-add MITTWALD_API_TOKEN=$(< ~/.config/mw/token)
```

**Comment by DaRe92** [comment]
There were several MITTWALD_API_TOKEN in the global_config. I deleted these and added a new one via `ddev config global --web-environment-add MITTWALD_API_TOKEN=${token}`. Now i have only one entry `MITTWALD_API_TOKEN=2056xxxx`.

However, I still receive the same error.

**Comment by martin-helmich** [comment]
@DaRe92 in #320, the handling of access tokens was reworked, so that there is no dependency on a globally configured `MITTWALD_API_TOKEN` variable anymore.

If the issues persists, could you provide the exact commands that you used to initialize your DDEV project, and an output of the `ddev debug configyaml` in your respective project (without any API tokens, of course)?

> Is it normal that the API token that is generated here does not appear in the profile?

No, that's not normal. If it doesn't appear in your profile, it's either not a valid API token (maybe it was revoked?), or was maybe issued for a different account?
