### ISSUE TITLE
starting mysqldump via SSH on project xxx. error

### ISSUE THREAD

**Issue by DaRe92** [mittwald/cli#326]
When i make `ddev pull` I receive the following error:

```
Authenticating...
Set installation ID to xxx
Set project ID to xxx
connecting to 'ssh.vehlage.project.host' as 'xxx@xxx'
Obtaining databases...

  Dumping a MySQL database

  ✅ fetching database. done
  ✅ fetching main user. done
  ✅ fetching project. done
  ✅ creating a temporary database user. done
  ❌ starting mysqldump via SSH on project p-xxx. error

     An error occurred during this operation:
     AxiosError: Request failed with status code 412

  ✅ removing temporary database user. done
╭──────────────────────────────────────────────────────────────────────────────╮
│ ERROR                                                                        │
│                                                                              │
│ An error occurred while executing this command:                              │
│                                                                              │
│   AxiosError: Request failed with status code 412                            │
│                                                                              │
│ If you believe this to be a bug, please open an issue at                     │
│ https://github.com/mittwald/cli/issues/new                                   │
│ (​https://github.com/mittwald/cli/issues/new​).                              │
╰──────────────────────────────────────────────────────────────────────────────╯

  ERROR STACK TRACE

  Please provide this when opening a bug report.

  AxiosError: Request failed with status code 412
      at settle (file:///usr/lib/node_modules/@mittwald/cli/node_modules/axios/lib/core/settle.js:19:12)
      at IncomingMessage.handleStreamEnd (file:///usr/lib/node_modules/@mittwald/cli/node_modules/axios/lib/adapters/http.js:589:11)
      at IncomingMessage.emit (node:events:529:35)
      at endReadableNT (node:internal/streams/readable:1400:12)
      at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
      at Axios.request (file:///usr/lib/node_modules/@mittwald/cli/node_modules/axios/lib/core/Axios.js:45:41)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async getSSHConnectionForProject (file:///usr/lib/node_modules/@mittwald/cli/dist/lib/ssh/project.js:3:29)
      at async executeViaSSH (file:///usr/lib/node_modules/@mittwald/cli/dist/lib/ssh/exec.js:5:28)
      at async FancyProcessRenderer.runStep (file:///usr/lib/node_modules/@mittwald/cli/dist/rendering/process/process_fancy.js:42:28)
      at async Dump.exec (file:///usr/lib/node_modules/@mittwald/cli/dist/commands/database/mysql/dump.js:69:9)
      at async Dump.run (file:///usr/lib/node_modules/@mittwald/cli/dist/rendering/react/ExecRenderBaseCommand.js:18:24)
      at async Dump._run (/usr/lib/node_modules/@mittwald/cli/node_modules/@oclif/core/lib/command.js:304:22)
      at async Config.runCommand (/usr/lib/node_modules/@mittwald/cli/node_modules/@oclif/core/lib/config/config.js:432:25)
      at async Object.run (/usr/lib/node_modules/@mittwald/cli/node_modules/@oclif/core/lib/main.js:87:16)

Pull failed: failed to exec set -eu -o pipefail

database_output="/var/www/html/.ddev/.downloads/db.sql.gz"
database_id="${MITTWALD_DATABASE_ID:-}"

if [[ -z "${database_id}" ]] ; then
  database_id=$(mw app get -ojson | jq -r 'if has("linkedDatabases") then ((.linkedDatabases[] | select(.purpose == "primary")).databaseId) else empty end')
fi

if [[ -n "${database_id:-}" ]] ; then
  mw database mysql dump "${database_id}" --gzip -o "${database_output}"
else
  echo "app has no linked database; skipping database import"
  echo "" | gzip > "${database_output}"
fi
 on web: exit status 1

```

**Comment by martin-helmich** [comment]
That was a bug in the alpha.39 version of the CLI, which was fixed with https://github.com/mittwald/cli/pull/322.

Can you rebuild your DDEV images with `ddev debug refresh` and see if the issue persists? That should pull the recent mw CLI into your image.
