### ISSUE TITLE
How does filter option work?

### ISSUE THREAD

**Issue by LukasFritzeDev** [mittwald/cli#58]
I’m not able to figure out how the `--filter` option of the list commands should be used. 

tried it using the command `project list`. I have tried every combination I was able to think about. Some examples
```
mw project list --filter="customerId=8b454f648fb5"
mw project list --filter "customerId=8b454f648fb5"
mw project list --filter "customerId=8b454f648fb5"
mw project list --filter="customer-id=8b454f648fb5"
```

Everything produce the same error:
```
│ ERROR                                                                        │
│                                                                              │
│ An error occurred while executing this command:                              │
│                                                                              │
│   Error: Filter flag has an invalid value                                    │
│                                                                              │
```

The [OCLIF documentation](https://oclif.io/docs/table/) provides this example:
```
$ example-cli users --filter="company=Group"
```

---

```
  ERROR STACK TRACE

  Please provide this when opening a bug report.

  Error: Filter flag has an invalid value
      at Table.display (/opt/homebrew/Cellar/mw/1.0.0-alpha.21/libexec/node_modules/@oclif/core/lib/cli-ux/styled/table.js:68:23)
      at Object.table (/opt/homebrew/Cellar/mw/1.0.0-alpha.21/libexec/node_modules/@oclif/core/lib/cli-ux/styled/table.js:271:39)
      at ListFormatter.log (file:///opt/homebrew/Cellar/mw/1.0.0-alpha.21/libexec/dist/esm/Formatter.js:31:12)
      at List.run (file:///opt/homebrew/Cellar/mw/1.0.0-alpha.21/libexec/dist/esm/ListBaseCommand.js:27:24)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async List._run (/opt/homebrew/Cellar/mw/1.0.0-alpha.21/libexec/node_modules/@oclif/core/lib/command.js:117:22)
      at async Config.runCommand (/opt/homebrew/Cellar/mw/1.0.0-alpha.21/libexec/node_modules/@oclif/core/lib/config/config.js:329:25)
      at async Object.run (/opt/homebrew/Cellar/mw/1.0.0-alpha.21/libexec/node_modules/@oclif/core/lib/main.js:89:16)
```

**Comment by martin-helmich** [comment]
OK, I found out by digging through the OCLIF source code, and this is ~~utterly stupid~~ maybe a tad unintuitive. The "filter" option matches (case-insensitively) the actual table header (not the underlying field name, mind):

https://github.com/oclif/core/blob/c992403175c40492a5b724af3c117c6a059b4843/src/cli-ux/styled/table.ts#L120-L122

So, the correct parameter in your case would be `--filter "customer id=[...]"` (also mind the quotes, since all that must of course be passed as a _single argument_).

I'm open to suggestions as to how this might be implemented more intuitively for users. 🤔

**Comment by LukasFritzeDev** [comment]
Oha. Who thinks of something like that?

Maybe the easiest way would be to add a sample to the developer handbook / readme as a first step?
